/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedDailyReportRouteImport } from './routes/_authenticated/daily-report'
import { Route as AuthenticatedDesignSystemRouteImport } from './routes/_authenticated/design-system'
import { Route as AuthenticatedExpensesRouteImport } from './routes/_authenticated/expenses'
import { Route as AuthenticatedImportRouteImport } from './routes/_authenticated/import'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedProfitRouteImport } from './routes/_authenticated/profit'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedReturnsRouteImport } from './routes/_authenticated/returns'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedCustomersIndexRouteImport } from './routes/_authenticated/customers.index'
import { Route as AuthenticatedCustomersIdRouteImport } from './routes/_authenticated/customers.$id'
import { Route as AuthenticatedOrdersIndexRouteImport } from './routes/_authenticated/orders.index'
import { Route as AuthenticatedOrdersIdRouteImport } from './routes/_authenticated/orders.$id'
import { Route as AuthenticatedProductsIndexRouteImport } from './routes/_authenticated/products.index'
import { Route as AuthenticatedProductsIdRouteImport } from './routes/_authenticated/products.$id'
import { Route as AuthenticatedSettingsCourierRouteImport } from './routes/_authenticated/settings.courier'
import { Route as AuthenticatedSettingsInvoiceRouteImport } from './routes/_authenticated/settings.invoice'
import { Route as ApiPublicCourierWebhookRouteImport } from './routes/api/public/courier-webhook'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDailyReportRoute =
  AuthenticatedDailyReportRouteImport.update({
    id: '/daily-report',
    path: '/daily-report',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDesignSystemRoute =
  AuthenticatedDesignSystemRouteImport.update({
    id: '/design-system',
    path: '/design-system',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExpensesRoute = AuthenticatedExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImportRoute = AuthenticatedImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfitRoute = AuthenticatedProfitRouteImport.update({
  id: '/profit',
  path: '/profit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReturnsRoute = AuthenticatedReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedCustomersIndexRoute =
  AuthenticatedCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomersIdRoute =
  AuthenticatedCustomersIdRouteImport.update({
    id: '/customers/$id',
    path: '/customers/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdersIndexRoute =
  AuthenticatedOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdersIdRoute = AuthenticatedOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductsIndexRoute =
  AuthenticatedProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductsIdRoute = AuthenticatedProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsCourierRoute =
  AuthenticatedSettingsCourierRouteImport.update({
    id: '/settings/courier',
    path: '/settings/courier',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsInvoiceRoute =
  AuthenticatedSettingsInvoiceRouteImport.update({
    id: '/settings/invoice',
    path: '/settings/invoice',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicCourierWebhookRoute = ApiPublicCourierWebhookRouteImport.update({
  id: '/api/public/courier-webhook',
  path: '/api/public/courier-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/daily-report': typeof AuthenticatedDailyReportRoute
  '/design-system': typeof AuthenticatedDesignSystemRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/import': typeof AuthenticatedImportRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profit': typeof AuthenticatedProfitRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/returns': typeof AuthenticatedReturnsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/customers/$id': typeof AuthenticatedCustomersIdRoute
  '/orders/$id': typeof AuthenticatedOrdersIdRoute
  '/products/$id': typeof AuthenticatedProductsIdRoute
  '/settings/courier': typeof AuthenticatedSettingsCourierRoute
  '/settings/invoice': typeof AuthenticatedSettingsInvoiceRoute
  '/api/public/courier-webhook': typeof ApiPublicCourierWebhookRoute
  '/customers/': typeof AuthenticatedCustomersIndexRoute
  '/orders/': typeof AuthenticatedOrdersIndexRoute
  '/products/': typeof AuthenticatedProductsIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteWithChildren
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/daily-report': typeof AuthenticatedDailyReportRoute
  '/design-system': typeof AuthenticatedDesignSystemRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/import': typeof AuthenticatedImportRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profit': typeof AuthenticatedProfitRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/returns': typeof AuthenticatedReturnsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/': typeof AuthenticatedIndexRoute
  '/customers/$id': typeof AuthenticatedCustomersIdRoute
  '/orders/$id': typeof AuthenticatedOrdersIdRoute
  '/products/$id': typeof AuthenticatedProductsIdRoute
  '/settings/courier': typeof AuthenticatedSettingsCourierRoute
  '/settings/invoice': typeof AuthenticatedSettingsInvoiceRoute
  '/api/public/courier-webhook': typeof ApiPublicCourierWebhookRoute
  '/customers': typeof AuthenticatedCustomersIndexRoute
  '/orders': typeof AuthenticatedOrdersIndexRoute
  '/products': typeof AuthenticatedProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/daily-report': typeof AuthenticatedDailyReportRoute
  '/_authenticated/design-system': typeof AuthenticatedDesignSystemRoute
  '/_authenticated/expenses': typeof AuthenticatedExpensesRoute
  '/_authenticated/import': typeof AuthenticatedImportRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/profit': typeof AuthenticatedProfitRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/returns': typeof AuthenticatedReturnsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/customers/$id': typeof AuthenticatedCustomersIdRoute
  '/_authenticated/orders/$id': typeof AuthenticatedOrdersIdRoute
  '/_authenticated/products/$id': typeof AuthenticatedProductsIdRoute
  '/_authenticated/settings/courier': typeof AuthenticatedSettingsCourierRoute
  '/_authenticated/settings/invoice': typeof AuthenticatedSettingsInvoiceRoute
  '/api/public/courier-webhook': typeof ApiPublicCourierWebhookRoute
  '/_authenticated/customers/': typeof AuthenticatedCustomersIndexRoute
  '/_authenticated/orders/': typeof AuthenticatedOrdersIndexRoute
  '/_authenticated/products/': typeof AuthenticatedProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/analytics'
    | '/daily-report'
    | '/design-system'
    | '/expenses'
    | '/import'
    | '/onboarding'
    | '/profit'
    | '/reports'
    | '/returns'
    | '/auth/callback'
    | '/customers/$id'
    | '/orders/$id'
    | '/products/$id'
    | '/settings/courier'
    | '/settings/invoice'
    | '/api/public/courier-webhook'
    | '/customers/'
    | '/orders/'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/analytics'
    | '/daily-report'
    | '/design-system'
    | '/expenses'
    | '/import'
    | '/onboarding'
    | '/profit'
    | '/reports'
    | '/returns'
    | '/auth/callback'
    | '/'
    | '/customers/$id'
    | '/orders/$id'
    | '/products/$id'
    | '/settings/courier'
    | '/settings/invoice'
    | '/api/public/courier-webhook'
    | '/customers'
    | '/orders'
    | '/products'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/analytics'
    | '/_authenticated/daily-report'
    | '/_authenticated/design-system'
    | '/_authenticated/expenses'
    | '/_authenticated/import'
    | '/_authenticated/onboarding'
    | '/_authenticated/profit'
    | '/_authenticated/reports'
    | '/_authenticated/returns'
    | '/auth/callback'
    | '/_authenticated/'
    | '/_authenticated/customers/$id'
    | '/_authenticated/orders/$id'
    | '/_authenticated/products/$id'
    | '/_authenticated/settings/courier'
    | '/_authenticated/settings/invoice'
    | '/api/public/courier-webhook'
    | '/_authenticated/customers/'
    | '/_authenticated/orders/'
    | '/_authenticated/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ApiPublicCourierWebhookRoute: typeof ApiPublicCourierWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/daily-report': {
      id: '/_authenticated/daily-report'
      path: '/daily-report'
      fullPath: '/daily-report'
      preLoaderRoute: typeof AuthenticatedDailyReportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/design-system': {
      id: '/_authenticated/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof AuthenticatedDesignSystemRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expenses': {
      id: '/_authenticated/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthenticatedExpensesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/import': {
      id: '/_authenticated/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthenticatedImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profit': {
      id: '/_authenticated/profit'
      path: '/profit'
      fullPath: '/profit'
      preLoaderRoute: typeof AuthenticatedProfitRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/returns': {
      id: '/_authenticated/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof AuthenticatedReturnsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/customers/': {
      id: '/_authenticated/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AuthenticatedCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers/$id': {
      id: '/_authenticated/customers/$id'
      path: '/customers/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof AuthenticatedCustomersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders/': {
      id: '/_authenticated/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AuthenticatedOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders/$id': {
      id: '/_authenticated/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof AuthenticatedOrdersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products/': {
      id: '/_authenticated/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AuthenticatedProductsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products/$id': {
      id: '/_authenticated/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof AuthenticatedProductsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/courier': {
      id: '/_authenticated/settings/courier'
      path: '/settings/courier'
      fullPath: '/settings/courier'
      preLoaderRoute: typeof AuthenticatedSettingsCourierRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/invoice': {
      id: '/_authenticated/settings/invoice'
      path: '/settings/invoice'
      fullPath: '/settings/invoice'
      preLoaderRoute: typeof AuthenticatedSettingsInvoiceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/courier-webhook': {
      id: '/api/public/courier-webhook'
      path: '/api/public/courier-webhook'
      fullPath: '/api/public/courier-webhook'
      preLoaderRoute: typeof ApiPublicCourierWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedDailyReportRoute: typeof AuthenticatedDailyReportRoute
  AuthenticatedDesignSystemRoute: typeof AuthenticatedDesignSystemRoute
  AuthenticatedExpensesRoute: typeof AuthenticatedExpensesRoute
  AuthenticatedImportRoute: typeof AuthenticatedImportRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedProfitRoute: typeof AuthenticatedProfitRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedReturnsRoute: typeof AuthenticatedReturnsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCustomersIdRoute: typeof AuthenticatedCustomersIdRoute
  AuthenticatedOrdersIdRoute: typeof AuthenticatedOrdersIdRoute
  AuthenticatedProductsIdRoute: typeof AuthenticatedProductsIdRoute
  AuthenticatedSettingsCourierRoute: typeof AuthenticatedSettingsCourierRoute
  AuthenticatedSettingsInvoiceRoute: typeof AuthenticatedSettingsInvoiceRoute
  AuthenticatedCustomersIndexRoute: typeof AuthenticatedCustomersIndexRoute
  AuthenticatedOrdersIndexRoute: typeof AuthenticatedOrdersIndexRoute
  AuthenticatedProductsIndexRoute: typeof AuthenticatedProductsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedDailyReportRoute: AuthenticatedDailyReportRoute,
  AuthenticatedDesignSystemRoute: AuthenticatedDesignSystemRoute,
  AuthenticatedExpensesRoute: AuthenticatedExpensesRoute,
  AuthenticatedImportRoute: AuthenticatedImportRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedProfitRoute: AuthenticatedProfitRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedReturnsRoute: AuthenticatedReturnsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCustomersIdRoute: AuthenticatedCustomersIdRoute,
  AuthenticatedOrdersIdRoute: AuthenticatedOrdersIdRoute,
  AuthenticatedProductsIdRoute: AuthenticatedProductsIdRoute,
  AuthenticatedSettingsCourierRoute: AuthenticatedSettingsCourierRoute,
  AuthenticatedSettingsInvoiceRoute: AuthenticatedSettingsInvoiceRoute,
  AuthenticatedCustomersIndexRoute: AuthenticatedCustomersIndexRoute,
  AuthenticatedOrdersIndexRoute: AuthenticatedOrdersIndexRoute,
  AuthenticatedProductsIndexRoute: AuthenticatedProductsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ApiPublicCourierWebhookRoute: ApiPublicCourierWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
